theme: jekyll-theme-minimal
title: Kamryn Parker Project Portfolio
description: A compilation of projects and coursework I have completed during my undergradute and gradute education.
logo: /images/Kamryn_Parker_Headshot.jpeg
