theme: jekyll-theme-minimal
title: Kamryn Parker Project Portfolio
description: My name is Kamryn Parker and I am currently a Master of Computer Science student at Boise State University (May 2023). I am interested in Data Science and how we can use data to make informed decsions to make a positive impact.
logo: /images/Kamryn_Parker_Headshot.jpeg
